version: '3'

services:
  metadata-db:
    image: postgres:10.9-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: metadata_local

  metadata-app:
    container_name: metadata-app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 4000:4000
    links:
      - metadata-db
    environment:
      DATABASE_URL: postgres://postgres:password@metadata-db/metadata_local
      SECRET_KEY_BASE: key-base
      MIX_ENV: prod
